#!/bin/zsh

# 清理
typeset -A key

# 绑定
bindkey "\e[1~" beginning-of-line
bindkey "\e[2~" quoted-insert
bindkey "\e[3~" delete-char
bindkey "\e[4~" end-of-line
# bindkey "\e[5~" history-beginning-search-backward-end
# bindkey "\e[6~" history-beginning-search-forward-end

bindkey "\e[1;5C" forward-word
bindkey "\eOc" emacs-forward-word

bindkey "\e[1;5D" backward-word
bindkey "\eOd" emacs-backward-word

# only backward -_-||
# bindkey "^H" backward-delete-word

# for rxvt
#bindkey "\e[8~" end-of-line
#bindkey "\e[7~" beginning-of-line

# for non RH/Debian xterm, can't hurt for RH/DEbian xterm
#bindkey "\eOH" beginning-of-line
#bindkey "\eOF" end-of-line

# for freebsd console
#bindkey "\e[H" beginning-of-line
#bindkey "\e[F" end-of-line

# completion in the middle of a line
bindkey '^i' expand-or-complete-prefix

#typeset -g -A key
#bindkey '^?' backward-delete-char
#bindkey '^[[7~' beginning-of-line
#bindkey '^[[5~' up-line-or-history
#bindkey '^[[3~' delete-char
#bindkey '^[[8~' end-of-line
#bindkey '^[[6~' down-line-or-history
#bindkey '^[[A' up-line-or-search
#bindkey '^[[D' backward-char
#bindkey '^[[B' down-line-or-search
#bindkey '^[[C' forward-char 
#bindkey '^[[2~' overwrite-mode
