#!/bin/zsh

# execute system profile.d
[[ -f /etc/profile ]] && . /etc/profile

export PATH=$PATH:$HOME/.local/bin

# zinit
if [ -f $HOME/.zsh/libs/zinit/zinit.zsh ]; then
    source $HOME/.zsh/libs/zinit/zinit.zsh

    autoload -Uz _zinit
    (( ${+_comps} )) && _comps[zinit]=_zinit

    # Two regular plugins loaded without investigating.
    zinit light zsh-users/zsh-autosuggestions
    zinit light zdharma/fast-syntax-highlighting

    # Plugin history-search-multi-word loaded with investigating.
    zinit load zdharma/history-search-multi-word

    # Load the pure theme, with zsh-async library that's bundled with it.
    # zinit ice pick"async.zsh" src"pure.zsh"
    # zinit light sindresorhus/pure

    # A glance at the new for-syntax – load all of the above
    # plugins with a single command. For more information see:
    # https://zdharma.org/zinit/wiki/For-Syntax/
    zinit for \
        light-mode  zsh-users/zsh-autosuggestions \
        light-mode  zdharma/fast-syntax-highlighting \
                    zdharma/history-search-multi-word

    # Binary release in archive, from GitHub-releases page.
    # After automatic unpacking it provides program "fzf".
    zinit ice from "gh-r" as"program"
    zinit load junegunn/fzf-bin

    zinit light zdharma/fast-syntax-highlighting

    # Vim repository on GitHub – a typical source code that needs compilation – Zinit
    # can manage it for you if you like, run `./configure` and other `make`, etc. stuff.
    # Ice-mod `pick` selects a binary program to add to $PATH. You could also install the
    # package under the path $ZPFX, see: http://zdharma.org/zinit/wiki/Compiling-programs
    #zinit ice as"program" atclone"rm -f src/auto/config.cache; ./configure" \
    #     atpull"%atclone" make pick"src/vim"
    #zinit light vim/vim

    # Scripts that are built at install (there's single default make target, "install",
    # and it constructs scripts by `cat'ing a few files). The make'' ice could also be:
    # `make"install PREFIX=$ZPFX"`, if "install" wouldn't be the only, default target.
    zinit ice as"program" pick"$ZPFX/bin/git-*" make"PREFIX=$ZPFX"
    zinit light tj/git-extras

    zinit ice atclone"dircolors -b LS_COLORS > c.zsh" atpull'%atclone' pick"c.zsh" nocompile'!'
    zinit light trapd00r/LS_COLORS

    zinit ice as"program" make'!' atclone'./direnv hook zsh > zhook.zsh' atpull'%atclone' src"zhook.zsh"
    zinit light direnv/direnv

    zinit light zpm-zsh/ssh

    # use powerlevel10k
    zinit ice depth=1; zinit light romkatv/powerlevel10k

    zinit ice blockf atpull'zinit creinstall -q .'
    zinit light zsh-users/zsh-completions
fi

. ~/.zsh/etc/history
. ~/.zsh/etc/completion
. ~/.zsh/etc/bindkey
. ~/.zsh/etc/alias
